### ISSUE TITLE
Markbot issue

### ISSUE THREAD

**Issue by hongnguyen11** [hongnguyen11/kraken-good-accessibility#1]
I have problem with Markbot. It keeps spinning forever in the Screenshot 650px-Nav Focus.
@charlie-quinn

**Comment by charlie-quinn** [comment]
This assignment has already been graded ✅.

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by hongnguyen11** [comment]
Hi Charlie,
I just checked the progress. It is like that
<img width="873" alt="Screen Shot 2019-12-10 at 12 59 51 PM" src="https://user-images.githubusercontent.com/43138193/70555584-53c3e400-1b4d-11ea-9f9a-9e081355ab30.png">
@charlie-quinn

**Comment by hongnguyen11** [comment]
Hi Charlie,
I just checked the progress. It says:
<img width="590" alt="Screen Shot 2019-12-10 at 1 04 35 PM" src="https://user-images.githubusercontent.com/43138193/70555777-b6b57b00-1b4d-11ea-9324-bddc83ed605e.png">
@charlie-quinn

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@hongnguyen11 ⚠️`Reminder: please close this issue since it has been resolved or expired.`
